### ISSUE TITLE
Crashes on OSX  10.10.2

### ISSUE THREAD

**Issue by CavalcanteLeo** [tyeen/BlockJump#4] opened 2015-01-09 13:29 UTC
Xcode crashes on lasted version of OSX (10.10.2), and can't even open xcode to work

**Comment by CavalcanteLeo** [comment] 2015-01-09 13:30
Xcode crashes on lasted version of OSX, and can't even open xcode to work

**Comment by tyeen** [comment] 2015-01-10 05:43
Since 10.10.2 is still in beta and it seems very unstable(like Chrome crash in the first 10.10.2 beta release), I don't have it on my Mac yet(the same machine for my work, I can't take the risk:).
But it's probably caused by the same reason described in #57 of FuzzyAutocomplete(looks like a system bug):
https://github.com/FuzzyAutocomplete/FuzzyAutocompletePlugin/pull/57
You may give it a try.

If this issue still happens after the final release of 10.10.2, I'll definitely look into it.

**Comment by tyeen** [comment] 2015-01-28 01:11
So today 10.10.2 is officially released. And for me, this plug-in works well on the new OS version. If no further feedback, I'd like to close this issue.

**Closed** 2015-01-31 09:37 UTC

**Comment by chenwenying** [comment] 2015-02-02 02:21
hi tyeen, 
I've been encountered with github crash issue when updating to the latest OS 10.10.2, can you help please? @tyeen

**Comment by tyeen** [comment] 2015-02-02 15:22
@chenwenying Can you describe the details? What is a "github crash"? Parts of the logs may help.
